In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [22]:
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw 

img = Image.open("./image.jpg")
draw = ImageDraw.Draw(img)

# font = ImageFont.truetype(<font-file>, <font-size>)
font = ImageFont.truetype("Candarab.ttf", 25)
# draw.text((x, y),"Sample Text",(r,g,b))

print(img.height)
slack = 20
text = ""
text_size = 20
text_width = len("random text ") * (text_size//2)
text = "random text " * (img.width // text_width)
mask = Image.new(mode="RGB", size=img.size, color = 'white')
mask_draw = ImageDraw.Draw(mask)
for i in range(img.height // text_size):
    draw.text((0, (i*text_size) + (i*slack)), text,(255,255,255), font=font)
    mask_draw.text((0, (i*text_size) + (i*slack)), text, (0,0,0), font=font)
img.save('./image-out.jpg')
fn = lambda x : 255 if x > 200 else 0
r = mask.convert('L').point(fn, mode='1')
r.save('./mask-out.jpg')

1024


In [4]:
import matplotlib.font_manager
l = matplotlib.font_manager.findSystemFonts(fontpaths=None, fontext='ttf')
list(filter(lambda x: 'arial' in x, l))

['C:\\Windows\\Fonts\\arial.ttf',
 'C:\\Windows\\Fonts\\arialbd.ttf',
 'C:\\WINDOWS\\Fonts\\arial.ttf',
 'C:\\Windows\\Fonts\\ariali.ttf',
 'C:\\Windows\\Fonts\\arialbi.ttf',
 'C:\\WINDOWS\\Fonts\\arialbd.ttf',
 'C:\\WINDOWS\\Fonts\\arialbi.ttf',
 'C:\\WINDOWS\\Fonts\\ariali.ttf']

In [5]:
torch.randint(3, 5, (1, ))

tensor([4])

In [20]:
# get value from torch (1, 1)
torch.randint(0, (250 * 20) // 100, (1, )).item()

38

In [23]:
img = Image.open("./image.jpg")
print(img.size)
mask = Image.new(mode="RGB", size=img.size, color = 'white')

(1024, 1024)


In [28]:
mask = np.array(mask)
print(mask.shape)
print(mask[0, 0, 0])
print(mask[0, 0, 1])
print(mask[0, 0, 2])

(1024, 1024, 3)
255
255
255


In [29]:
img = Image.open("./image.jpg")
im = np.array(img)
# zero out rectangle
im[0:100, 0:100, :] = 0
# save img
# img = Image.fromarray(im)
img.save('./image-out-test.jpg')

In [31]:
with open("./mit-words.txt", "r", encoding="utf-8") as f:
    words = f.read().splitlines()
    print(max([len(word) for word in words]))

22


In [39]:
np.random.choice([1, 2, 4, 5, 1], 2)
" ".join(np.random.choice(["eyad", "dedo", "fedo"], 6))

'eyad dedo fedo dedo eyad eyad'

In [2]:
from glob import glob
import os
glob(os.path.join('.', '*.jpg'))

['.\\image-out-test.jpg',
 '.\\image-out.jpg',
 '.\\image.jpg',
 '.\\mask-out.jpg']

In [1]:
from glob import glob

In [4]:
images = []
extensions = ['jpg', 'png', 'jpeg']
root_dir = './images'
for extension in extensions:
    images.extend(glob(os.path.join(root_dir, '**\*.{}'.format(extension))))
print(images)

['./images\\New folder\\8022.jpg', './images\\New folder\\Sorrow-Donato-1200.jpg', './images\\New folder\\189089972_324342139056174_5903225519993275786_n.png']


In [6]:
def f(nested=False):
    images = []
    extensions = ['jpg', 'png', 'jpeg']
    root_dir = './images'
    search_pattern = '*.{}' if not nested else '**/*.{}'
    for extension in extensions:
        images.extend(glob(os.path.join(root_dir, search_pattern.format(extension))))
    print(images)

In [1]:
import os

In [3]:
data_path = r"C:\Users\eyad\Pictures\Images Datasets\Filcker Faces thumbnails 128x128"
print(os.path.dirname(data_path))

C:\Users\eyad\Pictures\Images Datasets


In [8]:
d = {
    'names': {
        'max': 1,
        'cuts': 4
    }
}



{'max': 1, 'cuts': 4}


In [9]:
list(filter(os.path.isdir, os.listdir(r'C:\Users\eyad\Pictures\Images Datasets\2_cutouts_small_20px')))

[]

In [16]:
os.listdir(r'.')

['.git',
 '.gitignore',
 'dataset.py',
 'data_preprocessing',
 'lightning_logs',
 'main.py',
 'mit-words.txt',
 'README.md',
 'ShConv.py',
 'Shepard_Convolutional_Neural_Network.ipynb',
 'test.ipynb',
 'transforms.py',
 'utils.py',
 '__pycache__']

In [18]:
[d for d in os.listdir(r'C:\Users\eyad\Pictures\Images Datasets\2_cutouts_small_20px') if os.path.isdir(d)]

[]

In [22]:
t = [os.path.abspath(name) for name in os.listdir(r'.') if os.path.isdir(name)]
print(t)

['c:\\Users\\eyad\\Documents\\CODE\\Shepard-Convolutional-Neural-Network\\.git', 'c:\\Users\\eyad\\Documents\\CODE\\Shepard-Convolutional-Neural-Network\\data_preprocessing', 'c:\\Users\\eyad\\Documents\\CODE\\Shepard-Convolutional-Neural-Network\\lightning_logs', 'c:\\Users\\eyad\\Documents\\CODE\\Shepard-Convolutional-Neural-Network\\__pycache__']


In [34]:
data = {
            "original": {
                "root_path": "",
                "images_paths": []
            },
            "corrupted": {
                "root_path": "",
                "images_paths": []
            },
            "mask": {
                "root_path": "",
                "images_paths": []
            }
        }
for image_source in data:
    print(image_source)

original
corrupted
mask


In [37]:
from glob import glob

In [40]:
search_pattern = '*.{}'
glob(os.path.join(r'C:\Users\eyad\Pictures\Images Datasets\2_cutouts_small_20px\corrupted_20px', search_pattern.format('png')))

['C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00000.png',
 'C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00001.png',
 'C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00002.png',
 'C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00003.png',
 'C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00004.png',
 'C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00005.png',
 'C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00006.png',
 'C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00007.png',
 'C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00008.png',
 'C:\\Users\\eyad\\Pictures\\Images Datasets\\2_cutouts_small_20px\\corrupted_20px\\00009.png',
 'C:\\Users\\eyad\\Pictures\\Images Data

In [1]:
import torch

In [8]:
import os
print(os.path.basename(r"C:\Users\eyad\Pictures\Images Datasets\1_cutout_large_50px"))


1_cutout_large_50px


In the mask, ones are the known areas and zeros are the unknown.

In [5]:
t = torch.rand((5, 5))
print(t)
t[t>=0.7] = 1
t[t<0.7] = 0
print(t)

tensor([[0.6636, 0.2436, 0.2495, 0.8175, 0.3658],
        [0.8076, 0.1381, 0.8609, 0.9405, 0.6253],
        [0.9405, 0.6231, 0.5143, 0.8498, 0.2626],
        [0.8895, 0.6695, 0.9014, 0.3833, 0.7400],
        [0.9295, 0.1544, 0.5615, 0.4880, 0.0537]])
tensor([[0., 0., 0., 1., 0.],
        [1., 0., 1., 1., 0.],
        [1., 0., 0., 1., 0.],
        [1., 0., 1., 0., 1.],
        [1., 0., 0., 0., 0.]])
